#!/usr/bin/env python3
"""Generate `noeira/envs/robots/assets/so_arm101_tower.xml` from `so_arm101.xml`.

    pixi run python tools/soarm/bake_so_arm101_tower.py            # write
    pixi run python tools/soarm/bake_so_arm101_tower.py --check    # CI

THE FOLLOWER AS BUILT ON THE `so101-tower` RIG — `docs/camera-rig.md`.

`so_arm101.xml` is the stock arm, generated by `tests/robots/so_arm_bake.py`
and gated tolerance-0.0 against the upstream MJCF. The rig's follower differs
from stock in exactly ONE printed part and ONE camera:

  * the stock `Wrist_Roll_Follower_SO101` is replaced by the one-piece
    `Wrist_Cam_Mount_32x32_UVC_Module_SO101` (servo 6 + fixed jaw + a camera
    arm) — `camera-rig.md` §2;
  * the wrist camera sits on that arm's plate, through the IMX335 adapter, at
    the entrance-pupil point measured off the STL — §4.

So this file is a GENERATOR over the stock text, like the bake it derives
from: every substitution is a named, counted replacement, and `--check`
regenerates and diffs. A hand-edited copy of a 16 KB generated model is the
drift this tree keeps paying for (`_a_rule_written_inline_twice_drifts`).

## ⚠⚠ THE TWO MESHES SHARE ONE FRAME — MEASURED, NOT ASSUMED

The stock part's STL is in METRES; the mount's STL is in MILLIMETRES (hence
`scale="0.001 0.001 0.001"`). ⚠ The upstream file is ASCII STL (5.2 MB, 20 852
faces), which MuJoCo's decoder refuses; the vendored copy under `MESHDIR` is
the same triangles written as BINARY STL (1.0 MB), and the original is kept in
`projects/so101-tower/assets/hardware/`. Sliced at the servo pocket (z 20..60 mm, 60..100,
100..105.4) both meshes span the same x/y extents to 0.3 mm, so the mount is
authored in the stock part's frame and takes the stock geom's `pos`/`quat`
unchanged. The plate face the doc quotes — centre (2.50, 71.85, -3.21) mm,
normal (0, -0.4243, 0.9055) — is a 1713 mm² planar face of that mesh, 4.0 mm
from its opposite face: the plate. Both facts are recomputed from the STL by
`_measure_wrist_mesh` below and asserted before anything is written.

## THE CAMERA POSE

Mesh frame -> `gripper` body frame is the stock geom's transform,
`quat="0 1 0 0"` (a half-turn about x: y and z flip) plus its `pos`. The
entrance pupil is 19.0 mm along the plate normal from the plate face
(`PUPIL_ALONG_NORMAL_MM`, measured 2026-09-25: see there).

Image orientation: the board's hole pattern is symmetric, so "up" is how it was
screwed on. Read off the RECORDED frames (`projects/so101-tower/datasets/
cube-in-bowl`, wrist stream): the jaws are at the BOTTOM of the image. With the
optical axis pointing along the jaws that puts image-up AWAY from the wrist
along the plate — `xyaxes="-1 0 0  0 -0.9055 -0.4243"` in the body frame. The
model matches the capture; do not "fix" the image in software instead
(`camera-rig.md` §4).

## INTRINSICS

The IMX335 is a 170° fisheye and the tracer is a pinhole. `fovy` here is the
VIRTUAL pinhole the real frames are to be undistorted to — 90° horizontal at
4:3, i.e. fx = fy = 320 px, cx = 320, cy = 240 on 640x480, fovy =
2·atan(240/320) = 73.74°. Both rig cameras are the same module and share it.
"""
import argparse
import math
import os
import struct
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STOCK = "noeira/envs/robots/assets/so_arm101.xml"
OUT = "noeira/envs/robots/assets/so_arm101_tower.xml"
GRIPPER_STACK_EXTRA_M = 0.0065
"""How much further from the wrist_flex axis the rig's gripper body sits than
upstream's (bake step 4a). Measured 2026-09-24/25 on the rig: the fixed jaw's
tip is 172 mm from the wrist_flex axis by ruler against the model's 165.9, a
desk-touch fit reads +6.7 mm, while the FINGER itself matches the STL (the
moving jaw's hinge -> the fixed jaw's tip: 86 mm on the part, 85.7 in the
model; and the tip sits at the mesh tip in the median of 420 wrist frames,
where camera and jaw ride the same body). So the extra length is in the roll
servo / horn / mount stack: the whole body goes out, not the finger."""
LIFT_REST_STOP = -110.0 * np.pi / 180.0
"""shoulder_lift's lower joint limit on the rig (step 7): the real arm's rest
hard stop, -106.0 LeRobot deg + the measured -3.6 deg zero = -109.6, rounded
out to -110 deg."""
MESHDIR = "noeira/envs/robots/assets/so_arm101"
STOCK_MESH = "wrist_roll_follower_so101_v1"
MOUNT_MESH = "wrist_cam_mount_32x32_uvc_module_so101"

# `camera-rig.md` §4, in the mount's mesh frame, millimetres.
PLATE_FACE_MM = np.array([2.50, 71.85, -3.21])
PLATE_NORMAL = np.array([0.0, -0.4243, 0.9055])
PUPIL_ALONG_NORMAL_MM = 19.0
"""The camera's projection centre, from the plate face along its normal. Was
15.6 (adapter 3.0 + standoffs 5.0 + PCB 1.6 + ~6 guessed to the pupil).
MEASURED 2026-09-25: plate face -> the lens's front glass 24 mm (ruler, on
the tower's identical module + adapter); a small fisheye's entrance pupil
sits a few mm behind its front element (19-22). The overhead camera's
extrinsics fit (62 captures) put its projection centre 2.0 mm beyond the
15.6 stack (17.6, +-2-3 mm with the stand's push-fit slop in it). 19.0,
+-2. The wrist frames cannot settle it: the fixed finger runs radially from
the image centre, so its silhouette slides along itself with depth."""
PLATE_THICKNESS_MM = 4.0

# THE ARUCO MARKER taped on the back of the wrist camera's plate (step 8).
# DICT_4X4_50 id 7, the black square 30 mm (`calibrate_camera_extrinsics
# --marker-mm 30`); the 6x6 cells, border included, row 0 = the marker's +y
# edge, column 0 its -x edge — `cv2.aruco.generateImageMarker(DICT_4X4_50, 7,
# 6)`, asserted in `check`. 1 = white.
ARUCO_ID = 7
ARUCO_MM = 30.0
ARUCO_BITS = ["000000", "011000", "001000", "011110", "000100", "000000"]
# Albedos from the printed recording's overhead frames (40 detections, marker
# ~20 px): black cells 31, white cells up to 209, against the desk's 183 at
# albedo 0.81 — the marker faces up like the desk. Blur lifts the black.
ARUCO_BLACK_RGBA = "0.1 0.1 0.1 1"
ARUCO_WHITE_RGBA = "0.85 0.85 0.85 1"
ARUCO_GROUP = 5
"""Its own geom group, so the tracer's `legacy` look (groups 0 + 2) keeps
rendering the pre-marker scene byte for byte (`so101_tower_rig`)."""

# The virtual pinhole (see INTRINSICS above).
FOVY_DEG = 2.0 * math.degrees(math.atan(240.0 / 320.0))

# The stock geom's transform, as written in `so_arm101.xml`. Asserted present.
STOCK_GEOM_POS = "8.32667e-17 -0.000218214 0.000949706"
STOCK_GEOM_QUAT = "0 1 0 0"

STOCK_VISUAL = (
    '                <geom type="mesh" class="visual" pos="%s" quat="%s"'
    ' mesh="%s" material="%s_material"/>'
    % (STOCK_GEOM_POS, STOCK_GEOM_QUAT, STOCK_MESH, STOCK_MESH)
)
STOCK_COLLISION = STOCK_VISUAL.replace('class="visual"', 'class="collision"')
STOCK_COMMENT = "                <!-- Part %s -->" % STOCK_MESH
STOCK_MESH_ASSET = '    <mesh name="%s" file="%s.stl"/>' % (STOCK_MESH, STOCK_MESH)
STOCK_MATERIAL = (
    '    <material name="%s_material" rgba="1 0.82 0.12 1"/>' % STOCK_MESH
)
# The stock moving-jaw collision line in `so_arm101.xml`. Asserted present.
STOCK_JAW_COLLISION = (
    '                  <geom type="mesh" class="collision"'
    ' pos="-5.55112e-17 -5.55112e-17 0.0189"'
    ' quat="1 -0 3.00524e-16 -2.00834e-17" mesh="moving_jaw_so101_v1"'
    ' material="moving_jaw_so101_v1_material"/>'
)

# ⚠ THE JAW BOXES ARE STIFF, LIKE THE PROPS (`gen_tower_props.CONTACT`).
# A pair's softness is the AVERAGE of its two geoms', and the stock arm's
# geoms carry MuJoCo's defaults (solref 0.02, solimp 0.9 0.95): against the
# stiff brick the pair came out at solref 0.015 / solimp 0.95, and the 3.35 N
# squeeze sank each jaw 6-8 mm INTO the cube while holding it — MuJoCo
# itself, fed the recorded actions, reproduced our trajectory to 0.03 mrad
# and ended in the same penetration (2026-09-20), so it was the model, not
# the engine. The stiff pair keeps the jaws on the cube's faces.
JAW_CONTACT = 'solref="0.01 1" solimp="0.998 0.998 0.001"'

# The jaws' collision boxes: (name, centre, half-size), metres.
# FIXED JAW in the gripper body frame — the moving jaw is on +x, so the fixed
# finger's inner face is its max-x face: x -8 mm at the tip (z -104), -13 at
# z -64, -15 at z -42, then the servo pocket. Slices of the mesh:
#   z -104..-70  x -22..-9   y +-7.5     the finger tip segment (the mesh's
#                                         tip is at z -104.4: the box reaches it)
#   z  -70..-42  x -33..-13  y +-12      the finger base (outer side slopes)
#   z  -42..-12  x -35..+12  y +-24      the pocket, lower half
#   z  -12..0    x -17..+30  y -28..+24  the pocket, upper half (the servo)
FIXED_JAW_BOXES = [
    ("fixed_finger_tip",  (-0.0155,  0.000, -0.0872), (0.0065, 0.0075, 0.0172)),
    ("fixed_finger_base", (-0.02325, 0.000, -0.056), (0.00975, 0.012, 0.014)),
    ("gripper_pocket_low", (-0.0115, 0.000, -0.027), (0.0235, 0.024, 0.015)),
    ("gripper_pocket_top", (0.0065, -0.002, -0.006), (0.0235, 0.026, 0.006)),
]
# MOVING JAW in its body frame (hinge axis z; the finger runs along -y; its
# pad — the face toward the fixed jaw — is its min-x face). The stock geom's
# z offset (0.0189) is folded into these. Slices of the mesh:
#   y -84..-60  x -12.5..-2  z 12..26    the finger tip
#   y -60..-24  x  -8.5..+6  z  9..29    the finger
#   y -24..+10  x  +-10      z -5..43    the hinge block
MOVING_JAW_BOXES = [
    ("moving_jaw_tip",   (-0.00725, -0.072, 0.019), (0.00525, 0.012, 0.007)),
    ("moving_jaw_mid",   (-0.00125, -0.042, 0.019), (0.00725, 0.018, 0.010)),
    ("moving_jaw_hinge", (0.000,    -0.007, 0.019), (0.010,   0.017, 0.024)),
]

STOCK_CAM = (
    "                <!-- ADDITION: wrist camera, see so_arm_bake.py"
    " WRIST_CAM -->\n"
    '                <camera name="wrist_cam" pos="0 0.04 -0.04"'
    ' euler="-0.5 0.0 6.28" fovy="75"/>'
)


def load_stl(path):
    """Triangles [n, 3, 3] of a binary or ASCII STL, in the file's units."""
    b = open(path, "rb").read()
    if b[:5] == b"solid" and b"facet" in b[:400]:
        vs = []
        for line in b.decode(errors="ignore").splitlines():
            t = line.strip().split()
            if t and t[0] == "vertex":
                vs.append([float(x) for x in t[1:4]])
        return np.array(vs).reshape(-1, 3, 3)
    n = struct.unpack("<I", b[80:84])[0]
    a = np.frombuffer(
        b[84 : 84 + n * 50],
        dtype=np.dtype([("n", "<3f4"), ("v", "<9f4"), ("a", "<u2")]),
    )
    return a["v"].reshape(-1, 3, 3).astype(np.float64)


def _slab(v, axis, lo, hi):
    m = (v[:, axis] >= lo) & (v[:, axis] <= hi)
    return v[m]


def _measure_wrist_mesh():
    """The two facts the camera pose rests on, read off the STLs."""
    stock = load_stl(os.path.join(ROOT, MESHDIR, STOCK_MESH + ".stl"))
    mount = load_stl(os.path.join(ROOT, MESHDIR, MOUNT_MESH + ".stl"))
    sv = stock.reshape(-1, 3) * 1000.0  # metres -> mm
    mv = mount.reshape(-1, 3)
    # 1. same frame: the servo pocket's x/y extents agree slice by slice.
    for lo, hi in ((20, 60), (60, 100), (100, 105.4)):
        a = _slab(sv, 2, lo, hi)
        b = _slab(mv, 2, lo, hi)
        for k in (0, 1):
            for f in (np.min, np.max):
                da = abs(f(a[:, k]) - f(b[:, k]))
                assert da < 0.5, (
                    "stock and mount meshes disagree by %.2f mm on axis %d in"
                    " z[%g, %g]: they are NOT in one frame" % (da, k, lo, hi)
                )
    # 2. the plate: a planar face with the doc's normal, at the doc's centre,
    #    and its opposite face `PLATE_THICKNESS_MM` behind it.
    n = np.cross(mount[:, 1] - mount[:, 0], mount[:, 2] - mount[:, 0])
    area = np.linalg.norm(n, axis=1) / 2
    nn = n / np.maximum(np.linalg.norm(n, axis=1, keepdims=True), 1e-12)
    c = mount.mean(1)
    front = (area > 1e-6) & (nn @ PLATE_NORMAL > 0.999) & (c[:, 1] > 45)
    back = (area > 1e-6) & (nn @ (-PLATE_NORMAL) > 0.999) & (c[:, 1] > 45)
    for m, name in ((front, "front"), (back, "back")):
        assert area[m].sum() > 1000, "no %s plate face found" % name
    cf = (c[front] * area[front, None]).sum(0) / area[front].sum()
    cb = (c[back] * area[back, None]).sum(0) / area[back].sum()
    assert np.linalg.norm(cf - PLATE_FACE_MM) < 0.5, (
        "plate face centre %s vs the doc's %s" % (cf.round(2), PLATE_FACE_MM)
    )
    thick = float((cf - cb) @ PLATE_NORMAL)
    assert abs(thick - PLATE_THICKNESS_MM) < 0.2, (
        "plate thickness %.2f mm, doc says %g" % (thick, PLATE_THICKNESS_MM)
    )
    return cf, thick


def _quat_to_mat(q):
    w, x, y, z = q
    return np.array(
        [
            [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
            [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
            [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
        ]
    )


def camera_in_gripper_body():
    """(pos [m], xyaxes [6]) of the wrist camera in the `gripper` body frame.

    Derived from the doc's mesh-frame numbers and the stock geom's transform —
    the SAME rule `camera-rig.md` §6 spells out — so `--check` can compare it
    against what MuJoCo composes from the written attributes.
    """
    n = PLATE_NORMAL / np.linalg.norm(PLATE_NORMAL)
    pupil_mm = PLATE_FACE_MM + PUPIL_ALONG_NORMAL_MM * n
    R = _quat_to_mat([float(v) for v in STOCK_GEOM_QUAT.split()])
    p0 = np.array([float(v) for v in STOCK_GEOM_POS.split()])
    pos = R @ (pupil_mm / 1000.0) + p0
    axis = R @ n  # optical axis in the body frame
    z_cam = -axis
    # image-up: jaws at the bottom of the frame (see the module docstring).
    y_cam = -np.cross(z_cam, np.array([1.0, 0.0, 0.0]))
    y_cam /= np.linalg.norm(y_cam)
    x_cam = np.cross(y_cam, z_cam)
    return pos, np.concatenate([x_cam, y_cam])


def _mat_to_quat(R):
    """(w, x, y, z) of a proper rotation matrix."""
    w = math.sqrt(max(0.0, 1.0 + R[0, 0] + R[1, 1] + R[2, 2])) / 2.0
    x = math.copysign(math.sqrt(max(0.0, 1.0 + R[0, 0] - R[1, 1] - R[2, 2])) / 2.0, R[2, 1] - R[1, 2])
    y = math.copysign(math.sqrt(max(0.0, 1.0 - R[0, 0] + R[1, 1] - R[2, 2])) / 2.0, R[0, 2] - R[2, 0])
    z = math.copysign(math.sqrt(max(0.0, 1.0 - R[0, 0] - R[1, 1] + R[2, 2])) / 2.0, R[1, 0] - R[0, 1])
    return np.array([w, x, y, z])


def marker_in_gripper_body():
    """(centre [m], R [3x3]) of the ArUco marker in the `gripper` body frame:
    its columns are the marker's +x, +y and its normal (+z, out of the print).

    ON THE BACK FACE OF THE CAMERA PLATE, CENTRED — the front face's centre
    (where the lens is: the mount's 27 x 27 hole pattern is centred on it to
    0.0 mm) pushed `PLATE_THICKNESS_MM` back. Fitted independently from the 30
    extrinsics captures (`camera_overhead.txt.poses.txt`: marker corners
    solvePnP'd, gripper FK from the raw ticks through the measured zero, camera
    and offset solved together, rms 9.9 mm): normal (0.046, -0.399, 0.916),
    2.3 deg from the plate's; in-plane +x (-0.02, 0.92, 0.40) — the print's
    +y along body -x, the fixed jaw's side (orientation scatter 4.3 deg
    median); centre 6 mm from this one in-plane (inside the fit's noise, which
    trades with the camera's own xy), 2.5 mm into the plate.
    """
    n = PLATE_NORMAL / np.linalg.norm(PLATE_NORMAL)
    back_mm = PLATE_FACE_MM - PLATE_THICKNESS_MM * n
    R = _quat_to_mat([float(v) for v in STOCK_GEOM_QUAT.split()])
    p0 = np.array([float(v) for v in STOCK_GEOM_POS.split()])
    centre = R @ (back_mm / 1000.0) + p0
    ez = R @ (-n)
    ey = np.array([-1.0, 0.0, 0.0])
    ex = np.cross(ey, ez)
    return centre, np.stack([ex, ey, ez], axis=1)


def marker_geoms():
    """The marker as boxes: the black square, then each row's white runs
    0.2 mm proud of it. Visual only (group `ARUCO_GROUP`, no contacts)."""
    c, R = marker_in_gripper_body()
    q = _fmt(_mat_to_quat(R), 7)
    cell = ARUCO_MM / 6000.0
    out = []

    def box(name, u, v, hu, hv, lift, hz, mat):
        p = c + R @ np.array([u, v, lift])
        out.append(
            '                <geom type="box" name="%s" group="%d" contype="0"'
            ' conaffinity="0" pos="%s" quat="%s" size="%s" material="%s"/>'
            % (name, ARUCO_GROUP, _fmt(p, 7), q, _fmt([hu, hv, hz], 6), mat)
        )

    box("aruco_black", 0.0, 0.0, 3 * cell, 3 * cell, 0.0002, 0.0002, "aruco_black")
    k = 0
    for r, row in enumerate(ARUCO_BITS):
        col = 0
        while col < 6:
            if row[col] != "1":
                col += 1
                continue
            end = col
            while end < 6 and row[end] == "1":
                end += 1
            u = ((col + end) / 2.0 - 3.0) * cell
            v = (3.0 - (r + 0.5)) * cell
            box("aruco_white_%d" % k, u, v, (end - col) * cell / 2, cell / 2, 0.0005, 0.0001, "aruco_white")
            k += 1
            col = end
    return out


def _fmt(v, nd=6):
    return " ".join(("%.*g" % (nd, float(x) + 0.0)) for x in v)


def bake():
    src = open(os.path.join(ROOT, STOCK)).read()
    _measure_wrist_mesh()
    pos, xy = camera_in_gripper_body()

    def sub(old, new, what):
        assert src.count(old) == 1, "expected exactly one %s in %s" % (what, STOCK)
        return src.replace(old, new)

    src = sub(
        '<mujoco model="so101_new_calib">',
        '<mujoco model="so101_tower_follower">\n'
        "  <!-- RIG DEVIATION: elliptic friction cones with impratio 10. The"
        " upstream SO-101 ships MuJoCo's defaults (pyramidal, impratio 1),"
        " under which a pinched 25 mm cube CREEPS out of the jaw over seconds"
        " (task_grasp_feasibility.mojo, 2026-09-19). `impratio` raises the"
        " frictional-to-normal constraint impedance and has effect ONLY with"
        " elliptic cones (MuJoCo's own gripping advice); Menagerie's SO-100"
        " scene and the Robotiq 2F-85 ship exactly this pair, robosuite 20."
        " The family restates it with inherit_option=1. -->\n"
        '  <option cone="elliptic" impratio="10"/>',
        "model tag",
    )
    src = sub(
        "<!-- Generated using onshape-to-robot -->",
        "<!-- GENERATED by tools/soarm/bake_so_arm101_tower.py from"
        " so_arm101.xml — DO NOT EDIT. The so101-tower follower: the stock"
        " wrist roll replaced by the one-piece wrist camera mount, and the"
        " rig's wrist camera. See docs/camera-rig.md. -->\n"
        "<!-- Generated using onshape-to-robot -->",
        "provenance comment",
    )
    src = sub(
        STOCK_COMMENT,
        "                <!-- Part %s — RIG DEVIATION: replaces %s"
        " (Wrist_Cam_Mount_32x32_UVC_Module_SO101.stl, mm, same frame) -->"
        % (MOUNT_MESH, STOCK_MESH),
        "wrist part comment",
    )
    # ⚠⚠ THE MOUNT IS THE VISUAL GEOM ONLY; THE COLLISION GEOM STAYS THE STOCK
    # PART, plus a box for the camera arm. The collision path hulls every mesh
    # (`collision/hull_cache.mojo`), and the hull of the one-piece mount —
    # servo pocket, fixed jaw AND a camera arm 89 mm out — is a blob that
    # fills the pinch: `task_grasp_feasibility.mojo so101_tower_lift_brick`
    # held NOTHING down to a 12 mm cube with the mount as collision, where the
    # stock hull holds 24 mm. The stock part is the same servo pocket and jaw
    # (same mesh frame, measured above), so colliding with it is the rig's
    # jaw; the arm box is the camera arm's envelope in the body frame
    # (mesh x -15..20, y 45..89, z -15..5, through `quat="0 1 0 0"`).
    new_vis = STOCK_VISUAL.replace('mesh="%s"' % STOCK_MESH, 'mesh="%s"' % MOUNT_MESH).replace(
        'material="%s_material"' % STOCK_MESH, 'material="%s_material"' % MOUNT_MESH
    )
    src = sub(STOCK_VISUAL, new_vis, "visual wrist geom")
    # ⚠⚠ THE JAWS COLLIDE AS BOXES, NOT AS HULLS (2026-09-20). Every mesh
    # collides as its CONVEX HULL, and the stock part's hull — servo pocket
    # plus the fixed finger — spans the pinch cavity: measured against the
    # mesh, 50 cm^3 of hull with no surface within 3 mm of it, from the
    # finger's inner face (x -13 mm) to x +8 mm, over the finger's whole
    # length. A cube could never touch the real pad; it was pinched between a
    # ROUNDED PHANTOM surface and the moving jaw, whose own hull fills its
    # L-shape the same way. `task_grasp_feasibility.mojo` held the printed
    # cube at 4 of 250 placements on a +-3 cm grid, and under teleop it
    # slipped out where the real one does not. MuJoCo hulls the same meshes
    # (`mj_geomDistance`: the brick at the pinch centre is 1.5 mm INSIDE the
    # fixed hull at every jaw angle), so this is the asset, not the engine.
    # The boxes below are read off the meshes' z-slices (gripper frame) and
    # y-slices (jaw frame), +-2 mm; the inner faces are the ones that matter.
    src = sub(
        STOCK_COLLISION,
        "                <!-- RIG DEVIATION: the fixed jaw and the servo pocket as"
        " BOXES (see bake_so_arm101_tower.py: the mesh's hull filled the"
        " pinch) -->\n"
        + "\n".join(
            '                <geom type="box" class="collision" name="%s"'
            ' pos="%s" size="%s" %s/>' % (n, _fmt(np.array(p3)), _fmt(np.array(h3)), JAW_CONTACT)
            for n, p3, h3 in FIXED_JAW_BOXES
        )
        + "\n"
        "                <!-- RIG DEVIATION: the camera arm's envelope, as a box"
        " (see bake_so_arm101_tower.py) -->\n"
        '                <geom type="box" class="collision" pos="0.0025 -0.067 0.005"'
        ' size="0.0175 0.022 0.010" material="%s_material"/>' % MOUNT_MESH,
        "collision wrist geom",
    )
    src = sub(
        STOCK_JAW_COLLISION,
        "                  <!-- RIG DEVIATION: the moving jaw as BOXES (its hull"
        " filled the L; see bake_so_arm101_tower.py) -->\n"
        + "\n".join(
            '                  <geom type="box" class="collision" name="%s"'
            ' pos="%s" size="%s" %s/>' % (n, _fmt(np.array(p3)), _fmt(np.array(h3)), JAW_CONTACT)
            for n, p3, h3 in MOVING_JAW_BOXES
        ),
        "collision moving-jaw geom",
    )
    src = sub(
        STOCK_MESH_ASSET,
        STOCK_MESH_ASSET + "\n"
        '    <mesh name="%s" file="%s.stl" scale="0.001 0.001 0.001"/>'
        % (MOUNT_MESH, MOUNT_MESH),
        "wrist mesh asset",
    )
    src = sub(
        STOCK_MATERIAL,
        STOCK_MATERIAL + "\n"
        '    <material name="%s_material" rgba="0.92 0.92 0.92 1"/>' % MOUNT_MESH,
        "wrist material",
    )
    cam = (
        "                <!-- RIG CAMERA: the IMX335 on the wrist mount's plate,"
        " entrance pupil, image-up away from the wrist —"
        " tools/soarm/bake_so_arm101_tower.py, docs/camera-rig.md §4 -->\n"
        '                <camera name="wrist_cam" pos="%s" xyaxes="%s"'
        ' fovy="%.4f"/>' % (_fmt(pos), _fmt(xy), FOVY_DEG)
    )
    src = sub(STOCK_CAM, cam, "stock wrist camera")
    # 4a. THE GRIPPER BODY 6.5 mm FURTHER OUT along its roll axis
    #     (`GRIPPER_STACK_EXTRA_M`). The body's -z is the wrist frame's -y
    #     (from its quat), so only pos.y moves: -0.0611 -> -0.0676. Everything
    #     on the body — jaw, wrist camera, grasp_center, gripperframe — moves
    #     with it, and the roll axis stays the same line.
    src = sub(
        '<body name="gripper" pos="5.55112e-17 -0.0611 0.0181"',
        '<body name="gripper" pos="5.55112e-17 %.4f 0.0181"' % (-0.0611 - GRIPPER_STACK_EXTRA_M),
        "gripper body",
    )
    # 4b. `gripperframe` AT THE JAW'S TIP. Upstream puts the site at z -98.1
    #     in the gripper frame; the fixed finger's mesh (the stock part's and
    #     the mount's alike) ends at z -104.4 (x -13.6..-7.9 there), measured
    #     off the mesh in MuJoCo. So a tool that reads the site as "the tip"
    #     was 6.3 mm short: on the rig, FK of hand-guided touches read the
    #     tip ~13 mm high, half of it this (noeira-72, 2026-09-24; the rest is
    #     unresolved — a longer print, a lift zero, or the desk reference).
    #     x stays at the tip's inner face (-7.9), the orientation unchanged.
    src = sub(
        '<site group="3" name="gripperframe" pos="-0.0079 -0.000218121 -0.0981274"',
        '<site group="3" name="gripperframe" pos="-0.0079 -0.000218121 -0.1044"',
        "gripperframe site",
    )
    # 4c. THE PINCH CENTRE, as a site. `gripperframe` is the fixed jaw's TIP;
    #    a brick held by this jaw sits 3 cm above it and 2 cm towards the
    #    fixed jaw — (0.0221, 0.0012, -0.0681) in the gripper body, measured
    #    by `task_grasp_feasibility.mojo` (the held offset at rest, mapped
    #    through `xmat`). The family's placement table names THIS site as the
    #    gripper site, so the reach term and the goal words pull the object
    #    INTO the jaws; measured from the tip, 100k steps of SAC parked the
    #    jaw on the brick and never once had it between the fingers.
    src = sub(
        cam,
        cam + "\n"
        "                <!-- RIG ADDITION: the pinch centre — see"
        " bake_so_arm101_tower.py step 4c -->\n"
        '                <site group="3" name="grasp_center"'
        ' pos="0.0221 0.0012 -0.0681" size="0.004"/>',
        "wrist camera (site anchor)",
    )
    # 5. NO FLOOR, NO LIGHT, NO GROUNDPLANE. The stock model inlines
    #    `SO101/scene.xml`'s floor plane for the reach env. In a FAMILY the
    #    composer writes the floor and the light, and this base is attached
    #    5 mm UP (on the stand's plate): a floor carried here would be a
    #    second collision plane 5 mm above the desk, hiding the mat and
    #    catching every prop — measured: the first preview render showed the
    #    checker plane over the mat. The mocap `target` body stays (the
    #    config's `USES_MOCAP` expects it).
    src = sub(
        "    <!-- from SO101/scene.xml -->\n"
        '    <light pos="0 0 3.5" dir="0 0 -1" directional="true"/>\n'
        '    <geom name="floor" size="0 0 0.05" pos="0 0 0" type="plane"'
        ' material="groundplane"/>\n',
        "    <!-- RIG DEVIATION: no floor and no light here — the family's"
        " composer writes both (tools/soarm/bake_so_arm101_tower.py) -->\n",
        "inlined floor",
    )
    src = sub(
        "    <!-- from SO101/scene.xml -->\n"
        '    <texture type="2d" name="groundplane" builtin="checker"'
        ' mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"\n'
        '      markrgb="0.8 0.8 0.8" width="300" height="300"/>\n'
        '    <material name="groundplane" texture="groundplane"'
        ' texuniform="true" texrepeat="5 5" reflectance="0.2"/>\n',
        "",
        "groundplane asset",
    )
    # 6. WHITE PARTS. The Waveshare SO-ARM101 kit on the rig is printed in
    #    white (every recorded frame), where the reference model's material
    #    is the SO-ARM100's orange. The tracer renders what the material
    #    says, and a sim-to-real frame should not differ by the arm's colour.
    #    ⚠ 0.78, NOT 0.92: the grey the rig's cameras record the white parts
    #    at under the family's calibrated lights (so101_tower.family,
    #    2026-09-24: real arm 143 / jaw 146 overhead, jaw 130 wrist; albedo =
    #    real / light level, the cameras' geometric mean). 0.92 rendered
    #    clipped white.
    n = src.count('rgba="1 0.82 0.12 1"')
    assert n == 11, "expected 11 orange materials, found %d" % n
    src = src.replace('rgba="1 0.82 0.12 1"', 'rgba="0.78 0.78 0.76 1"')
    # 6b. THE CAMERA MOUNT TOO — it is not one of the 11 orange parts (the
    #    bake adds it above at 0.92), and step 6 missed it until 2026-09-25:
    #    the mount, which carries the fixed jaw, rendered 151 on the wrist
    #    camera against the real 124 and 169 overhead against 146 (printed
    #    recording, MuJoCo segmentation at the recorded states). Albedo
    #    0.92 x real / sim = 0.755 wrist, 0.795 overhead: 0.78. Neutral
    #    (0.78, not 0.76, in blue) so `so101_tower_rig`'s legacy look can put
    #    this one part back to its old 0.92 grey exactly.
    mount_old = '    <material name="%s_material" rgba="0.92 0.92 0.92 1"/>' % MOUNT_MESH
    src = sub(
        mount_old,
        '    <material name="%s_material" rgba="0.78 0.78 0.78 1"/>' % MOUNT_MESH,
        "mount material",
    )
    # 7. SHOULDER_LIFT REACHES THE REAL ARM'S REST. Folded at rest the real
    #    follower sits on its lift hard stop at -106.0 LeRobot deg, which with
    #    the measured zero (`robot/so101/sim_map.tower_follower_zero_deg`,
    #    -3.6) is -109.6 deg in model terms — past the stock joint limit of
    #    -100 deg, where 40% of the cube-in-bowl recording sits. The JOINT's
    #    lower limit moves to -110 deg so the family's rest pose
    #    (`so101_tower.family base_qpos=`) is a state the sim can hold. The
    #    ACTUATOR's `ctrlrange` stays +-100 deg: it is the action map (every
    #    recorded `.demo` word is normalised onto it, `So101TowerUnits`), and
    #    the real arm too leaves the stop on its first command.
    src = sub(
        '<joint axis="0 0 1" name="shoulder_lift" type="hinge"'
        ' range="-1.7453292519943224 1.7453292519943366" class="sts3215"/>',
        "<!-- RIG DEVIATION: the lower limit is the real arm's rest hard stop"
        " (-110 deg), see bake_so_arm101_tower.py step 7; ctrlrange unchanged -->\n"
        '          <joint axis="0 0 1" name="shoulder_lift" type="hinge"'
        ' range="%.16g 1.7453292519943366" class="sts3215"/>' % LIFT_REST_STOP,
        "shoulder_lift joint",
    )
    # 8. THE ARUCO MARKER STAYS ON THE RIG — the extrinsics target, taped on
    #    the back of the wrist camera's plate and in every frame the printed
    #    recording has of the gripper (the overhead camera sees it whenever
    #    the jaw points down). Deployment keeps it, so the sim draws it:
    #    `marker_in_gripper_body` for where, `ARUCO_*` for what.
    grasp = (
        '                <site group="3" name="grasp_center"'
        ' pos="0.0221 0.0012 -0.0681" size="0.004"/>'
    )
    src = sub(
        grasp,
        grasp + "\n"
        "                <!-- RIG ADDITION: the ArUco marker (DICT_4X4_50 id %d,"
        " %g mm) on the back of the camera plate, visual only, group %d —"
        " bake_so_arm101_tower.py step 8 -->\n" % (ARUCO_ID, ARUCO_MM, ARUCO_GROUP)
        + "\n".join(marker_geoms()),
        "grasp_center site (marker anchor)",
    )
    mount_mat = '    <material name="%s_material" rgba="0.78 0.78 0.78 1"/>' % MOUNT_MESH
    src = sub(
        mount_mat,
        mount_mat + "\n"
        '    <material name="aruco_black" rgba="%s"/>\n'
        '    <material name="aruco_white" rgba="%s"/>' % (ARUCO_BLACK_RGBA, ARUCO_WHITE_RGBA),
        "mount material (marker anchor)",
    )
    return src


def check(text):
    """MuJoCo composes the written camera to the derived pose."""
    import mujoco

    m = mujoco.MjModel.from_xml_path(os.path.join(ROOT, OUT))
    ref = mujoco.MjModel.from_xml_path(os.path.join(ROOT, STOCK))
    assert m.nsite == ref.nsite + 1, (m.nsite, ref.nsite)
    assert mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_SITE, "grasp_center") >= 0
    assert m.ncam == 1 and m.nbody == ref.nbody and m.nq == ref.nq, (
        "tower model counts drifted from stock: ncam %d nbody %d nq %d"
        % (m.ncam, m.nbody, m.nq)
    )
    # the floor gone (-1 geom) and the camera arm box added (+1); one mesh
    # more (the mount beside the stock part); one light fewer, no texture,
    # the groundplane material gone and the mount's added
    # +5 geoms: the two jaw collision MESHES became 4 + 3 boxes (the camera-arm
    # box was already counted against the stock's follower collision mesh).
    # step 8: the marker's boxes (the black square + the white runs) and its
    # two materials.
    n_marker = len(marker_geoms())
    assert m.ngeom == ref.ngeom + 5 + n_marker and m.nmesh == ref.nmesh + 1, (m.ngeom, m.nmesh)
    assert m.nlight == ref.nlight - 1 and m.ntex == 0 and m.nmat == ref.nmat + 2
    mk = [i for i in range(m.ngeom) if (mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_GEOM, i) or "").startswith("aruco_")]
    assert len(mk) == n_marker, mk
    for i in mk:
        assert m.geom_group[i] == ARUCO_GROUP and m.geom_contype[i] == 0 and m.geom_conaffinity[i] == 0
    try:
        import cv2

        want = cv2.aruco.generateImageMarker(
            cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50), ARUCO_ID, 6
        )
        got = np.array([[255 * int(ch) for ch in row] for row in ARUCO_BITS])
        assert np.array_equal(want, got), "ARUCO_BITS is not id %d:\n%s" % (ARUCO_ID, want // 255)
    except ImportError:
        pass
    # step 4a: the gripper body sits GRIPPER_STACK_EXTRA_M further out
    gb = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, "gripper")
    rb = mujoco.mj_name2id(ref, mujoco.mjtObj.mjOBJ_BODY, "gripper")
    assert abs((m.body_pos[gb][1] - ref.body_pos[rb][1]) + GRIPPER_STACK_EXTRA_M) < 1e-9, m.body_pos[gb]
    # step 7: the lift JOINT reaches the real rest stop, its ACTUATOR does not
    j = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT, "shoulder_lift")
    a = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_ACTUATOR, "shoulder_lift")
    assert abs(m.jnt_range[j][0] - LIFT_REST_STOP) < 1e-12, m.jnt_range[j]
    assert np.array_equal(m.actuator_ctrlrange[a], ref.actuator_ctrlrange[a])
    d = mujoco.MjData(m)
    mujoco.mj_forward(m, d)
    b = m.cam_bodyid[0]
    assert mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_BODY, b) == "gripper"
    Rb = d.xmat[b].reshape(3, 3)
    pos_body = Rb.T @ (d.cam_xpos[0] - d.xpos[b])
    mat_body = Rb.T @ d.cam_xmat[0].reshape(3, 3)
    pos, xy = camera_in_gripper_body()
    dp = np.linalg.norm(pos_body - pos)
    dx = np.linalg.norm(mat_body[:, 0] - xy[:3])
    dy = np.linalg.norm(mat_body[:, 1] - xy[3:])
    assert dp < 1e-6 and dx < 1e-4 and dy < 1e-4, (
        "MuJoCo's composed wrist camera disagrees with the derivation:"
        " |dpos| %.2e |dx| %.2e |dy| %.2e" % (dp, dx, dy)
    )
    axis = -mat_body[:, 2]
    # the axis must point along the jaws (body -z) and back toward them (+y)
    assert axis[2] < -0.9 and axis[1] > 0.4, "optical axis %s" % axis.round(4)
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    os.chdir(ROOT)
    text = bake()
    if args.check:
        on_disk = open(OUT).read() if os.path.exists(OUT) else None
        if on_disk != text:
            print("STALE: %s differs from what the bake produces" % OUT)
            return 1
        m = check(text)
        pos, xy = camera_in_gripper_body()
        print("ok: %s is current; MuJoCo composes wrist_cam at %s in `gripper`"
              " (ncam %d, nbody %d)" % (OUT, _fmt(pos, 4), m.ncam, m.nbody))
        return 0
    open(OUT, "w").write(text)
    pos, xy = camera_in_gripper_body()
    print("wrote %s" % OUT)
    print("  wrist_cam pos (gripper body, m):", _fmt(pos, 5))
    print("  wrist_cam xyaxes:", _fmt(xy, 4), "| fovy %.4f" % FOVY_DEG)
    try:
        check(text)
        print("  MuJoCo agrees with the derivation")
    except ImportError:
        print("  (mujoco not importable here; run --check where it is)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
