# GENERATED by noeira_max/graph_mojo/gen/gen_mojo_builder.py from
# max/_core/dialects/rmo/__init__.pyi (via rmo_schema.json).
# DO NOT EDIT: rerun extract_schema.py, then gen_mojo_builder.py.
"""Every `rmo` op that MAX's stubs describe, as a typed Mojo function.

Each function takes a `GraphBackend` first, then the op's arguments in the
stub's order: operands as `Value`s, attributes as Mojo types, and, where
the stub has no inferring constructor, the result type. 121 ops;
skipped (no form a typed generator can map): MoResizeLinearOp, MoResizeNearestOp.
"""

from .backend import Dim, GraphBackend, OpArgs, TensorType, Value


def mo_reduce_arg_max[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """This op is equivalent to reduce_max, but returns indices instead of
    values.

    `rmo.mo.reduce.arg_max` (`MoReduceArgMaxOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoReduceArgMaxOp", "rmo.mo.reduce.arg_max")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_arg_min[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """This op is equivalent to reduce_min, but returns indices instead of
    values.

    `rmo.mo.reduce.arg_min` (`MoReduceArgMinOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoReduceArgMinOp", "rmo.mo.reduce.arg_min")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_max[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Reduces `input` elements across `axis` to their maximum, changing that
    axis's dimension to 1 in the output shape.

    `rmo.mo.reduce.max` (`MoReduceMaxOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoReduceMaxOp", "rmo.mo.reduce.max")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_min[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Reduces `input` elements across `axis` to their minimum, changing that
    axis's dimension to 1 in the output shape.

    `rmo.mo.reduce.min` (`MoReduceMinOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoReduceMinOp", "rmo.mo.reduce.min")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_atanh[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Computes `atanh(x)`, where `x` is input tensor.

    `rmo.mo.atanh` (`MoAtanhOp`); the caller supplies the result type."""
    var a = OpArgs("MoAtanhOp", "rmo.mo.atanh")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_abs[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns `abs(x)`, where `x` is the input tensors.

    `rmo.mo.abs` (`MoAbsOp`); the caller supplies the result type."""
    var a = OpArgs("MoAbsOp", "rmo.mo.abs")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_add[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise addition.

    `rmo.mo.add` (`MoAddOp`); the caller supplies the result type."""
    var a = OpArgs("MoAddOp", "rmo.mo.add")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_and[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x and y`, where `x` and `y` are input boolean tensors.

    `rmo.mo.and` (`MoAndOp`); the caller supplies the result type."""
    var a = OpArgs("MoAndOp", "rmo.mo.and")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_arg_nonzero[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns a tensor of coordinates of the nonzero values in the given
    tensor. The return value is a 2D tensor of shape [nnz x rank_in], where
    nnz is the number of nonzero elements in the input tensor, and rank_in
    is the rank of the input tensor. Coordinates are generated in row-major
    order.

    `rmo.mo.arg_nonzero` (`MoArgNonzeroOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoArgNonzeroOp", "rmo.mo.arg_nonzero")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_avg_pool_ceil_mode_true[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter_shape: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
    count_boundary: Bool,
) raises -> Value:
    """Computes average pooling with the given filter shape, strides, and
    dilations.

    `rmo.mo.avg_pool_ceil_mode_true` (`MoAvgPoolCeilModeTrueOp`); the caller
    supplies the result type."""
    var a = OpArgs("MoAvgPoolCeilModeTrueOp", "rmo.mo.avg_pool_ceil_mode_true")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter_shape", filter_shape)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.attr_bool_attr("count_boundary", count_boundary)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_avg_pool[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter_shape: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
    count_boundary: Bool,
) raises -> Value:
    """Computes average pooling with the given filter shape, strides, and
    dilations.

    `rmo.mo.avg_pool` (`MoAvgPoolOp`); the caller supplies the result type."""
    var a = OpArgs("MoAvgPoolOp", "rmo.mo.avg_pool")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter_shape", filter_shape)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.attr_bool_attr("count_boundary", count_boundary)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_linalg_band_part[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    num_lower: Value,
    num_upper: Value,
    exclude: Value,
) raises -> Value:
    """Copies a tensor setting everything outside central (diagonal) band of
    the matrices to zero, where all but the last two axes are effectively
    batches, and the last two axes define sub matrices.

    `rmo.mo.linalg.band_part` (`MoLinalgBandPartOp`); the caller supplies
    the result type."""
    var a = OpArgs("MoLinalgBandPartOp", "rmo.mo.linalg.band_part")
    a.result("result", result)
    a.operand("input", input)
    a.operand("num_lower", num_lower)
    a.operand("num_upper", num_upper)
    a.operand("exclude", exclude)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_bottom_k[B: GraphBackend](
    mut b: B,
    values: TensorType,
    indices: TensorType,
    input: Value,
    _k: Value,
    axis: Value,
    sorted: Value,
) raises -> List[Value]:
    """Computes the bottom (lowest) values and their corresponding indices in a
    tensor along a specified axis. Returned values along the axis are always
    sorted (stable).

    `rmo.mo.bottom_k` (`MoBottomKOp`); the caller supplies the result type."""
    var a = OpArgs("MoBottomKOp", "rmo.mo.bottom_k")
    a.result("values", values)
    a.result("indices", indices)
    a.operand("input", input)
    a.operand("_k", _k)
    a.operand("axis", axis)
    a.operand("sorted", sorted)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results^


def mo_broadcast_shape[B: GraphBackend](
    mut b: B,
    shape: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Given two tensors representing shapes, calculate the result of
    broadcasting the shapes.

    `rmo.mo.broadcast_shape` (`MoBroadcastShapeOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoBroadcastShapeOp", "rmo.mo.broadcast_shape")
    a.result("shape", shape)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_broadcast_to[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    new_shape: Value,
) raises -> Value:
    """Broadcast the given `input` to the shape represented in `newShape`.

    `rmo.mo.broadcast_to` (`MoBroadcastToOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoBroadcastToOp", "rmo.mo.broadcast_to")
    a.result("result", result)
    a.operand("input", input)
    a.operand("new_shape", new_shape)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_cast[B: GraphBackend](mut b: B, input: Value, dtype: DType) raises -> Value:
    """Casts the given data, changing from one dtype to another.

    `rmo.mo.cast` (`MoCastOp`); result types inferred."""
    var a = OpArgs("MoCastOp", "rmo.mo.cast")
    a.operand("input", input)
    a.attr_dtype("dtype", dtype)
    var results = b.add_op(a^)
    return results[0].copy()


def mo_ceil[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the elementwise smallest integer greater than `x`, where `x` is
    input tensor.

    `rmo.mo.ceil` (`MoCeilOp`); the caller supplies the result type."""
    var a = OpArgs("MoCeilOp", "rmo.mo.ceil")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_conv[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
    num_groups: Value,
    input_layout: String,
    filter_layout: String,
) raises -> Value:
    """Computes the convolution product of the input with the given filter,
    strides, dilations, paddings, and groups.

    `rmo.mo.conv` (`MoConvOp`); the caller supplies the result type."""
    var a = OpArgs("MoConvOp", "rmo.mo.conv")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter", filter)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.operand("num_groups", num_groups)
    a.attr_string_attr("input_layout", input_layout)
    a.attr_string_attr("filter_layout", filter_layout)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_conv_transpose[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
    output_paddings: Value,
    input_layout: String,
    filter_layout: String,
) raises -> Value:
    """This op effectively computes the gradient of a convolution with respect
    to its input (as if the original convolution operation had the same
    filter and hyperparameters as this op). A visualization of the
    computation can be found in https://d2l.ai/chapter_computer-
    vision/transposed-conv.html.

    `rmo.mo.conv_transpose` (`MoConvTransposeOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoConvTransposeOp", "rmo.mo.conv_transpose")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter", filter)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.operand("output_paddings", output_paddings)
    a.attr_string_attr("input_layout", input_layout)
    a.attr_string_attr("filter_layout", filter_layout)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_cos[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns `cos(x)`, where `x` is input tensor.

    `rmo.mo.cos` (`MoCosOp`); the caller supplies the result type."""
    var a = OpArgs("MoCosOp", "rmo.mo.cos")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_cumsum[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
    exclusive: Int,
    reverse: Int,
) raises -> Value:
    """Returns the cumulative summation of input tensors along an axis. By
    default, it copies the first element as is. If the `exclusive` attribute
    is set to 1, then the first element is excluded. The `reverse` attribute
    causes the summation to be done in the opposite direction of the axis.

    `rmo.mo.cumsum` (`MoCumsumOp`); the caller supplies the result type."""
    var a = OpArgs("MoCumsumOp", "rmo.mo.cumsum")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.attr_index("exclusive", exclusive)
    a.attr_index("reverse", reverse)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_div[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise division.

    `rmo.mo.div` (`MoDivOp`); the caller supplies the result type."""
    var a = OpArgs("MoDivOp", "rmo.mo.div")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_equal[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x == y`, where `x` and `y` are input tensors.

    `rmo.mo.equal` (`MoEqualOp`); the caller supplies the result type."""
    var a = OpArgs("MoEqualOp", "rmo.mo.equal")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_erf[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Computes the Gauss error function of the input tensor elements.

    `rmo.mo.erf` (`MoErfOp`); the caller supplies the result type."""
    var a = OpArgs("MoErfOp", "rmo.mo.erf")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_exp[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns `exp(x)`, where `x` is the input tensor.

    `rmo.mo.exp` (`MoExpOp`); the caller supplies the result type."""
    var a = OpArgs("MoExpOp", "rmo.mo.exp")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_floor[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the elementwise largest integer not greater than `x`, where `x`
    is input tensor.

    `rmo.mo.floor` (`MoFloorOp`); the caller supplies the result type."""
    var a = OpArgs("MoFloorOp", "rmo.mo.floor")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_gather_nd[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    indices: Value,
    batch_dims: Int,
) raises -> Value:
    """Variant of `mo.gather` that accepts multi-dimensional indices.

    `rmo.mo.gather_nd` (`MoGatherNdOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoGatherNdOp", "rmo.mo.gather_nd")
    a.result("result", result)
    a.operand("input", input)
    a.operand("indices", indices)
    a.attr_index("batch_dims", batch_dims)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_gather[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    indices: Value,
    axis: Int,
) raises -> Value:
    """Gathers slices from input's axis according to indices.

    `rmo.mo.gather` (`MoGatherOp`); the caller supplies the result type."""
    var a = OpArgs("MoGatherOp", "rmo.mo.gather")
    a.result("result", result)
    a.operand("input", input)
    a.operand("indices", indices)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_gelu[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the exact GELU activation `0.5 * x * (1 + erf(x / sqrt(2)))`,
    where `x` is the input tensor.

    `rmo.mo.gelu` (`MoGeluOp`); the caller supplies the result type."""
    var a = OpArgs("MoGeluOp", "rmo.mo.gelu")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_gelu_quick[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the quick approximation of GELU `x * sigmoid(1.702 * x)`, where
    `x` is the input tensor.

    `rmo.mo.gelu_quick` (`MoGeluQuickOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoGeluQuickOp", "rmo.mo.gelu_quick")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_gelu_tanh[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the tanh approximation of GELU `0.5 * x * (1 +
    tanh(0.7978845608028654 * (x + 0.044715 * x^3)))`, where `x` is the
    input tensor.

    `rmo.mo.gelu_tanh` (`MoGeluTanhOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoGeluTanhOp", "rmo.mo.gelu_tanh")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_greater_equal[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x >= y`, where `x` and `y` are input tensors.

    `rmo.mo.greater_equal` (`MoGreaterEqualOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoGreaterEqualOp", "rmo.mo.greater_equal")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_greater[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x > y`, where `x` and `y` are input tensors.

    `rmo.mo.greater` (`MoGreaterOp`); the caller supplies the result type."""
    var a = OpArgs("MoGreaterOp", "rmo.mo.greater")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_is_inf[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
) raises -> Value:
    """Returns true if `x` represents a floating point Inf, where `x` is input
    tensor.

    `rmo.mo.is_inf` (`MoIsInfOp`); the caller supplies the result type."""
    var a = OpArgs("MoIsInfOp", "rmo.mo.is_inf")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_is_nan[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
) raises -> Value:
    """Returns true if `x` represents a floating point NaN, where `x` is input
    tensor.

    `rmo.mo.is_nan` (`MoIsNanOp`); the caller supplies the result type."""
    var a = OpArgs("MoIsNanOp", "rmo.mo.is_nan")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_log1p[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns `log(1 + x)`, maintaining accuracy for small `x` that could
    otherwise lead to floating-point roundings of the kind `1 + x = 1`.

    `rmo.mo.log1p` (`MoLog1pOp`); the caller supplies the result type."""
    var a = OpArgs("MoLog1pOp", "rmo.mo.log1p")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_log[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns the natural logarithm, `log(x)`.

    `rmo.mo.log` (`MoLogOp`); the caller supplies the result type."""
    var a = OpArgs("MoLogOp", "rmo.mo.log")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_logsoftmax[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Returns `log(softmax(x))`, where `x` is input tensor.

    `rmo.mo.reduce.logsoftmax` (`MoReduceLogsoftmaxOp`); the caller supplies
    the result type."""
    var a = OpArgs("MoReduceLogsoftmaxOp", "rmo.mo.reduce.logsoftmax")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_max[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise maximum.

    `rmo.mo.max` (`MoMaxOp`); the caller supplies the result type."""
    var a = OpArgs("MoMaxOp", "rmo.mo.max")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_max_pool_ceil_mode_true[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter_shape: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
) raises -> Value:
    """Computes max pooling with the given filter shape, strides, and
    dilations.

    `rmo.mo.max_pool_ceil_mode_true` (`MoMaxPoolCeilModeTrueOp`); the caller
    supplies the result type."""
    var a = OpArgs("MoMaxPoolCeilModeTrueOp", "rmo.mo.max_pool_ceil_mode_true")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter_shape", filter_shape)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_max_pool[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    filter_shape: Value,
    strides: Value,
    dilations: Value,
    paddings: Value,
) raises -> Value:
    """Computes max pooling with the given filter shape, strides, and
    dilations.

    `rmo.mo.max_pool` (`MoMaxPoolOp`); the caller supplies the result type."""
    var a = OpArgs("MoMaxPoolOp", "rmo.mo.max_pool")
    a.result("result", result)
    a.operand("input", input)
    a.operand("filter_shape", filter_shape)
    a.operand("strides", strides)
    a.operand("dilations", dilations)
    a.operand("paddings", paddings)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_mean[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Reduces `input` elements across `axis` to their mean value, changng that
    axis's dimension to 1.

    `rmo.mo.reduce.mean` (`MoReduceMeanOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoReduceMeanOp", "rmo.mo.reduce.mean")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_min[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise minimum.

    `rmo.mo.min` (`MoMinOp`); the caller supplies the result type."""
    var a = OpArgs("MoMinOp", "rmo.mo.min")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_mod[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise modulus.

    `rmo.mo.mod` (`MoModOp`); the caller supplies the result type."""
    var a = OpArgs("MoModOp", "rmo.mo.mod")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_mul[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise multiplication.

    `rmo.mo.mul` (`MoMulOp`); the caller supplies the result type."""
    var a = OpArgs("MoMulOp", "rmo.mo.mul")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_mutable_load[B: GraphBackend](
    mut b: B,
    out_tensor: TensorType,
    in_buffer: Value,
    in_chain: Value,
) raises -> List[Value]:
    """The `rmo.mo.mutable_load` op.

    `rmo.mo.mutable_load` (`MoMutableLoadOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoMutableLoadOp", "rmo.mo.mutable_load")
    a.result("out_tensor", out_tensor)
    a.result_chain("out_chain")
    a.operand("in_buffer", in_buffer)
    a.param_decls("output_param_decls")
    a.operand("in_chain", in_chain)
    var results = b.add_op(a^)
    return results^


def mo_mutable_store[B: GraphBackend](
    mut b: B,
    in_buffer: Value,
    in_tensor: Value,
    in_chain: Value,
) raises -> Value:
    """The `rmo.mo.mutable_store` op.

    `rmo.mo.mutable_store` (`MoMutableStoreOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoMutableStoreOp", "rmo.mo.mutable_store")
    a.result_chain("out_chain")
    a.operand("in_buffer", in_buffer)
    a.operand("in_tensor", in_tensor)
    a.param_decls("output_param_decls")
    a.operand("in_chain", in_chain)
    var results = b.add_op(a^)
    return results[0].copy()


def mo_mutable_store_slice[B: GraphBackend](
    mut b: B,
    in_buffer: Value,
    slice: Value,
    start: Value,
    stop: Value,
    step: Value,
    in_chain: Value,
) raises -> Value:
    """The `rmo.mo.mutable_store_slice` op.

    `rmo.mo.mutable_store_slice` (`MoMutableStoreSliceOp`); the caller
    supplies the result type."""
    var a = OpArgs("MoMutableStoreSliceOp", "rmo.mo.mutable_store_slice")
    a.result_chain("out_chain")
    a.operand("in_buffer", in_buffer)
    a.operand("slice", slice)
    a.operand("start", start)
    a.operand("stop", stop)
    a.operand("step", step)
    a.param_decls("output_param_decls")
    a.operand("in_chain", in_chain)
    var results = b.add_op(a^)
    return results[0].copy()


def mo_negative[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns `-x`, where `x` is input tensor.

    `rmo.mo.negative` (`MoNegativeOp`); the caller supplies the result type."""
    var a = OpArgs("MoNegativeOp", "rmo.mo.negative")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_non_maximum_suppression[B: GraphBackend](
    mut b: B,
    output: TensorType,
    boxes: Value,
    scores: Value,
    max_output_boxes_per_class: Value,
    iou_threshold: Value,
    score_threshold: Value,
) raises -> Value:
    """Filters out boxes that have high intersection-over-union (IOU).

    `rmo.mo.non_maximum_suppression` (`MoNonMaximumSuppressionOp`); the
    caller supplies the result type."""
    var a = OpArgs("MoNonMaximumSuppressionOp", "rmo.mo.non_maximum_suppression")
    a.result("output", output)
    a.operand("boxes", boxes)
    a.operand("scores", scores)
    a.operand("max_output_boxes_per_class", max_output_boxes_per_class)
    a.operand("iou_threshold", iou_threshold)
    a.operand("score_threshold", score_threshold)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_not_equal[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns elementwise `x != y`, where `x` and `y` are input tensors.

    `rmo.mo.not_equal` (`MoNotEqualOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoNotEqualOp", "rmo.mo.not_equal")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_not[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns `not x` on given input, where input is a boolean tensor.

    `rmo.mo.not` (`MoNotOp`); the caller supplies the result type."""
    var a = OpArgs("MoNotOp", "rmo.mo.not")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_or[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x or y`, where `x` and `y` are input boolean tensors.

    `rmo.mo.or` (`MoOrOp`); the caller supplies the result type."""
    var a = OpArgs("MoOrOp", "rmo.mo.or")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_pad_constant[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    paddings: Value,
    constant: Value,
) raises -> Value:
    """Pads the `input` tensor with a scalar tensor `constant` according to the
    `paddings`. Assumes input has rank `N`, the `paddings` tensor should
    have shape `(2 * N)`, where each consecutive pair of elements has the
    form `[before, after]`, indicating how many of `constant` to add before
    and after the contents of `input` in that dimension. The size of each
    dimension D of the padded output is: `paddings[2*D] + input.dim(D) +
    paddings[2*D+1]`.

    `rmo.mo.pad_constant` (`MoPadConstantOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoPadConstantOp", "rmo.mo.pad_constant")
    a.result("result", result)
    a.operand("input", input)
    a.operand("paddings", paddings)
    a.operand("constant", constant)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_pad_reflect[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    paddings: Value,
) raises -> Value:
    """Pads the `input` tensor by reflecting it according to the `paddings`.
    Assumes input has rank `N`, the `paddings` tensor should have shape `(2
    * N)`, where each consecutive pair of elements has the form `[before,
    after]`, indicating how many of `constant` to add before and after the
    contents of `input` in that dimension. The size of each dimension D of
    the padded output is: `paddings[2*D] + input.dim(D) + paddings[2*D+1]`.

    `rmo.mo.pad_reflect` (`MoPadReflectOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoPadReflectOp", "rmo.mo.pad_reflect")
    a.result("result", result)
    a.operand("input", input)
    a.operand("paddings", paddings)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_pad_repeat[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    paddings: Value,
) raises -> Value:
    """Pads the `input` tensor by repeating border values according to
    `paddings`. Assumes input has rank `N`, the `paddings` tensor should
    have shape `(2 * N)`, where each consecutive pair of elements has the
    form `[before, after]`, indicating how many of `constant` to add before
    and after the contents of `input` in that dimension. The size of each
    dimension D of the padded output is: `paddings[2*D] + input.dim(D) +
    paddings[2*D+1]`.

    `rmo.mo.pad_repeat` (`MoPadRepeatOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoPadRepeatOp", "rmo.mo.pad_repeat")
    a.result("result", result)
    a.operand("input", input)
    a.operand("paddings", paddings)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_pow[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise power. Allows mixed precision
    operands.

    `rmo.mo.pow` (`MoPowOp`); the caller supplies the result type."""
    var a = OpArgs("MoPowOp", "rmo.mo.pow")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_random_normal[B: GraphBackend](
    mut b: B,
    result: TensorType,
    shape: Value,
    mean: Value,
    variance: Value,
    seed: Value,
) raises -> Value:
    """Returns a tensor with shape `shape` populated with random values from a
    normal distribution, with the mean of the distribution equal to `mean`
    and the standard deviation equal to `variance`.

    `rmo.mo.random.normal` (`MoRandomNormalOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoRandomNormalOp", "rmo.mo.random.normal")
    a.result("result", result)
    a.operand("shape", shape)
    a.operand("mean", mean)
    a.operand("variance", variance)
    a.operand("seed", seed)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_random_uniform[B: GraphBackend](
    mut b: B,
    result: TensorType,
    shape: Value,
    lower_bound: Value,
    upper_bound: Value,
    seed: Value,
) raises -> Value:
    """Returns a tensor with shape `shape` populated with random values from a
    uniform distribution on the half-open interval [lowerBound, upperBound).

    `rmo.mo.random.uniform` (`MoRandomUniformOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoRandomUniformOp", "rmo.mo.random.uniform")
    a.result("result", result)
    a.operand("shape", shape)
    a.operand("lower_bound", lower_bound)
    a.operand("upper_bound", upper_bound)
    a.operand("seed", seed)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_range[B: GraphBackend](
    mut b: B,
    result: TensorType,
    start: Value,
    limit: Value,
    step: Value,
) raises -> Value:
    """Creates a sequence of numbers. The sequence goes from `start` with
    increments of size `step` up to (but not including) `limit`. All
    arguments are mandatory and must have the same element type.

    `rmo.mo.range` (`MoRangeOp`); the caller supplies the result type."""
    var a = OpArgs("MoRangeOp", "rmo.mo.range")
    a.result("result", result)
    a.operand("start", start)
    a.operand("limit", limit)
    a.operand("step", step)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_add[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Reduces `input` elements across `axis` to their sum, changing that
    axis's dimension to 1 in the output shape.

    `rmo.mo.reduce.add` (`MoReduceAddOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoReduceAddOp", "rmo.mo.reduce.add")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_mul[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Reduces `input` elements across `axis` to their product, changing that
    axis's dimension to 1 in the output shape.

    `rmo.mo.reduce.mul` (`MoReduceMulOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoReduceMulOp", "rmo.mo.reduce.mul")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_relu[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns `max(0, x)`, where `x` is the input tensor.

    `rmo.mo.relu` (`MoReluOp`); the caller supplies the result type."""
    var a = OpArgs("MoReluOp", "rmo.mo.relu")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reshape[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    new_shape: Value,
) raises -> Value:
    """Reshape the `input` tensor to the shape represented in `newShape`.

    `rmo.mo.reshape` (`MoReshapeOp`); the caller supplies the result type."""
    var a = OpArgs("MoReshapeOp", "rmo.mo.reshape")
    a.result("result", result)
    a.operand("input", input)
    a.operand("new_shape", new_shape)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_resize_bicubic[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    size: Value,
) raises -> Value:
    """Resizes a tensor to a new shape using the bicubic interpolation
    algorithm.

    `rmo.resize.bicubic` (`MoResizeBicubicOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoResizeBicubicOp", "rmo.resize.bicubic")
    a.result("result", result)
    a.operand("input", input)
    a.operand("size", size)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_roi_align[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    rois: Value,
    output_height: Value,
    output_width: Value,
    spatial_scale: Value,
    sampling_ratio: Value,
    aligned: Bool,
    mode: String,
) raises -> Value:
    """ROI align consumes an input tensor and regions of interest in which to
    apply pooling.

    `rmo.mo.roi_align` (`MoRoiAlignOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoRoiAlignOp", "rmo.mo.roi_align")
    a.result("result", result)
    a.operand("input", input)
    a.operand("rois", rois)
    a.operand("output_height", output_height)
    a.operand("output_width", output_width)
    a.operand("spatial_scale", spatial_scale)
    a.operand("sampling_ratio", sampling_ratio)
    a.attr_bool_attr("aligned", aligned)
    a.attr_string_attr("mode", mode)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_round[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the elementwise nearest integer, with ties going away from zero.

    `rmo.mo.round` (`MoRoundOp`); the caller supplies the result type."""
    var a = OpArgs("MoRoundOp", "rmo.mo.round")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_rsqrt[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns `1/sqrt(x)`, where `x` is the input tensor.

    `rmo.mo.rsqrt` (`MoRsqrtOp`); the caller supplies the result type."""
    var a = OpArgs("MoRsqrtOp", "rmo.mo.rsqrt")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_add[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
    axis: Value,
) raises -> Value:
    """Produces an output tensor by scattering elements from updates to input
    according to indices, and it stores the sum of elements with duplicate
    indices.

    `rmo.mo.scatter.add` (`MoScatterAddOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoScatterAddOp", "rmo.mo.scatter.add")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.operand("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_max[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
    axis: Value,
) raises -> Value:
    """Produces an output tensor by scattering elements from updates to input
    according to indices, and it stores the maximum of elements with
    duplicate indices.

    `rmo.mo.scatter.max` (`MoScatterMaxOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoScatterMaxOp", "rmo.mo.scatter.max")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.operand("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_min[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
    axis: Value,
) raises -> Value:
    """Produces an output tensor by scattering elements from updates to input
    according to indices, and it stores the minimum of elements with
    duplicate indices.

    `rmo.mo.scatter.min` (`MoScatterMinOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoScatterMinOp", "rmo.mo.scatter.min")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.operand("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_mul[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
    axis: Value,
) raises -> Value:
    """Produces an output tensor by scattering elements from updates to input
    according to indices, and it stores the product of elements with
    duplicate indices.

    `rmo.mo.scatter.mul` (`MoScatterMulOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoScatterMulOp", "rmo.mo.scatter.mul")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.operand("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_nd_add[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
) raises -> Value:
    """Produces an output tensor by scattering slices from updates to input
    according to indices, and it stores the sum of any duplicate indices.

    `rmo.mo.scatter_nd.add` (`MoScatterNdAddOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoScatterNdAddOp", "rmo.mo.scatter_nd.add")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_nd_max[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
) raises -> Value:
    """Produces an output tensor by scattering slices from updates to input
    according to indices, and it stores the maximum of any duplicate
    indices.

    `rmo.mo.scatter_nd.max` (`MoScatterNdMaxOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoScatterNdMaxOp", "rmo.mo.scatter_nd.max")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_nd_min[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
) raises -> Value:
    """Produces an output tensor by scattering slices from updates to input
    according to indices, and it stores the minimum of any duplicate
    indices.

    `rmo.mo.scatter_nd.min` (`MoScatterNdMinOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoScatterNdMinOp", "rmo.mo.scatter_nd.min")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_nd_mul[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
) raises -> Value:
    """Produces an output tensor by scattering slices from updates to input
    according to indices, and it stores the product of any duplicate
    indices.

    `rmo.mo.scatter_nd.mul` (`MoScatterNdMulOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoScatterNdMulOp", "rmo.mo.scatter_nd.mul")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter_nd[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
) raises -> Value:
    """Produces an output tensor by scattering slices from updates to input
    according to indices.

    `rmo.mo.scatter_nd` (`MoScatterNdOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoScatterNdOp", "rmo.mo.scatter_nd")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_scatter[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    updates: Value,
    indices: Value,
    axis: Int,
) raises -> Value:
    """Produces an output tensor by scattering elements from updates to input
    according to indices.

    `rmo.mo.scatter` (`MoScatterOp`); the caller supplies the result type."""
    var a = OpArgs("MoScatterOp", "rmo.mo.scatter")
    a.result("result", result)
    a.operand("input", input)
    a.operand("updates", updates)
    a.operand("indices", indices)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_select[B: GraphBackend](
    mut b: B,
    result: TensorType,
    cond: Value,
    x: Value,
    y: Value,
) raises -> Value:
    """Returns `cond ? x : y` (element-wise), where `cond`, `x` and `y` are
    input tensors.

    `rmo.mo.select` (`MoSelectOp`); the caller supplies the result type."""
    var a = OpArgs("MoSelectOp", "rmo.mo.select")
    a.result("result", result)
    a.operand("cond", cond)
    a.operand("x", x)
    a.operand("y", y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_shape_of[B: GraphBackend](
    mut b: B,
    shape: TensorType,
    input: Value,
) raises -> Value:
    """Calculates the runtime shape of the given tensor as a tensor.

    `rmo.mo.shape_of` (`MoShapeOfOp`); the caller supplies the result type."""
    var a = OpArgs("MoShapeOfOp", "rmo.mo.shape_of")
    a.result("shape", shape)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_sigmoid[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the sigmoid activation `1 / (1 + exp(-x))`, where `x` is the
    input tensor.

    `rmo.mo.sigmoid` (`MoSigmoidOp`); the caller supplies the result type."""
    var a = OpArgs("MoSigmoidOp", "rmo.mo.sigmoid")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_silu[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the SiLU (Swish) activation `x * sigmoid(x)`, where `x` is the
    input tensor.

    `rmo.mo.silu` (`MoSiluOp`); the caller supplies the result type."""
    var a = OpArgs("MoSiluOp", "rmo.mo.silu")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_sin[B: GraphBackend](mut b: B, result: TensorType, input: Value) raises -> Value:
    """Returns `sin(x)`, where `x` is input tensor.

    `rmo.mo.sin` (`MoSinOp`); the caller supplies the result type."""
    var a = OpArgs("MoSinOp", "rmo.mo.sin")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_slice[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    start: Value,
    stop: Value,
    step: Value,
) raises -> Value:
    """Returns a new tensor with a subset of the elements from an N-dimensional
    `input` tensor. The subset is chosen using the `start`, `stop`, and
    `step` 1D index tensors; each index tensor has N elements, one for each
    dimension of the `input` tensor.

    `rmo.mo.slice` (`MoSliceOp`); the caller supplies the result type."""
    var a = OpArgs("MoSliceOp", "rmo.mo.slice")
    a.result("result", result)
    a.operand("input", input)
    a.operand("start", start)
    a.operand("stop", stop)
    a.operand("step", step)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_reduce_softmax[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    axis: Int,
) raises -> Value:
    """Returns `exp(input) / sum(exp(input))`, where `x` is input tensor.

    `rmo.mo.reduce.softmax` (`MoReduceSoftmaxOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoReduceSoftmaxOp", "rmo.mo.reduce.softmax")
    a.result("result", result)
    a.operand("input", input)
    a.attr_index("axis", axis)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_sqrt[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns `sqrt(x)`, where `x` is the input tensor.

    `rmo.mo.sqrt` (`MoSqrtOp`); the caller supplies the result type."""
    var a = OpArgs("MoSqrtOp", "rmo.mo.sqrt")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_squeeze_shape[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_shape: Value,
    remove_indices: Value,
) raises -> Value:
    """Calculates the shape from squeeze like operators. Given an input shape
    vector representing a tensor of rank `N`, and a list of indices of
    length `M`, returns a new shape vector representing a tensor of rank `N
    - M`. The indices represent the 0-based index of dimensions in the
    original rank `N` tensor.

    `rmo.mo.squeeze_shape` (`MoSqueezeShapeOp`); the caller supplies the
    result type."""
    var a = OpArgs("MoSqueezeShapeOp", "rmo.mo.squeeze_shape")
    a.result("result", result)
    a.operand("input_shape", input_shape)
    a.operand("remove_indices", remove_indices)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_sub[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Does a non-broadcasted elementwise subtraction.

    `rmo.mo.sub` (`MoSubOp`); the caller supplies the result type."""
    var a = OpArgs("MoSubOp", "rmo.mo.sub")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_tanh[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Computes `tanh(x)`, where `x` is input tensor.

    `rmo.mo.tanh` (`MoTanhOp`); the caller supplies the result type."""
    var a = OpArgs("MoTanhOp", "rmo.mo.tanh")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_tile[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    repeats: Value,
) raises -> Value:
    """Returns a new Tensor as the result of copying the input tensor N_i times
    on each dimension, where N_i = tiles[i].

    `rmo.mo.tile` (`MoTileOp`); the caller supplies the result type."""
    var a = OpArgs("MoTileOp", "rmo.mo.tile")
    a.result("result", result)
    a.operand("input", input)
    a.operand("repeats", repeats)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_transpose[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
    perm: Value,
) raises -> Value:
    """Returns a new Tensor as the result of permuting the dimensions of the
    input tensor according to the value of perm.

    `rmo.mo.transpose` (`MoTransposeOp`); the caller supplies the result
    type."""
    var a = OpArgs("MoTransposeOp", "rmo.mo.transpose")
    a.result("result", result)
    a.operand("input", input)
    a.operand("perm", perm)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_trunc[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input: Value,
) raises -> Value:
    """Returns the elementwise integer from truncating the decimal. Also known
    as round-toward-zero.

    `rmo.mo.trunc` (`MoTruncOp`); the caller supplies the result type."""
    var a = OpArgs("MoTruncOp", "rmo.mo.trunc")
    a.result("result", result)
    a.operand("input", input)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mo_xor[B: GraphBackend](
    mut b: B,
    result: TensorType,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `x xor y`, where `x` and `y` are input boolean tensors.

    `rmo.mo.xor` (`MoXorOp`); the caller supplies the result type."""
    var a = OpArgs("MoXorOp", "rmo.mo.xor")
    a.result("result", result)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def add[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise add operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.add` (`AddOp`); result types inferred."""
    var a = OpArgs("AddOp", "rmo.add")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def and_[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise and comparison operation with implicit
    broadcasting.

    `rmo.and` (`AndOp`); result types inferred."""
    var a = OpArgs("AndOp", "rmo.and")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def avg_pool[B: GraphBackend](
    mut b: B,
    input: Value,
    filter_shape: List[Dim],
    strides: List[Dim],
    dilations: List[Dim],
    paddings: List[Dim],
    ceil_mode: Bool,
    count_boundary: Bool,
) raises -> Value:
    """Computes average pooling with the given filter shape, strides, and
    dilations.

    `rmo.avg_pool` (`AvgPoolOp`); result types inferred."""
    var a = OpArgs("AvgPoolOp", "rmo.avg_pool")
    a.operand("input", input)
    a.attr_shape("filter_shape", filter_shape)
    a.attr_shape("strides", strides)
    a.attr_shape("dilations", dilations)
    a.attr_shape("paddings", paddings)
    a.attr_bool("ceil_mode", ceil_mode)
    a.attr_bool("count_boundary", count_boundary)
    var results = b.add_op(a^)
    return results[0].copy()


def broadcast_like[B: GraphBackend](
    mut b: B,
    input: Value,
    shape_like: Value,
) raises -> Value:
    """Equivalent to the following:

    `rmo.broadcast_like` (`BroadcastLikeOp`); result types inferred."""
    var a = OpArgs("BroadcastLikeOp", "rmo.broadcast_like")
    a.operand("input", input)
    a.operand("shape_like", shape_like)
    var results = b.add_op(a^)
    return results[0].copy()


def broadcast_to[B: GraphBackend](
    mut b: B,
    input: Value,
    new_shape: List[Dim],
) raises -> Value:
    """Broadcasts the input tensor to the specified shape.

    `rmo.broadcast_to` (`BroadcastToOp`); result types inferred."""
    var a = OpArgs("BroadcastToOp", "rmo.broadcast_to")
    a.operand("input", input)
    a.attr_shape("new_shape", new_shape)
    var results = b.add_op(a^)
    return results[0].copy()


def conv[B: GraphBackend](
    mut b: B,
    input: Value,
    filter: Value,
    strides: List[Dim],
    dilations: List[Dim],
    paddings: List[Dim],
    num_groups: Int,
    input_layout: Optional[String] = None,
) raises -> Value:
    """Computes the convolution product of the input with the given filter,
    strides, dilations, paddings, and groups.

    `rmo.conv` (`ConvOp`); result types inferred."""
    var a = OpArgs("ConvOp", "rmo.conv")
    a.operand("input", input)
    a.operand("filter", filter)
    a.attr_shape("strides", strides)
    a.attr_shape("dilations", dilations)
    a.attr_shape("paddings", paddings)
    a.attr_int("num_groups", num_groups)
    if input_layout:
        a.attr_string("input_layout", input_layout.value())
    var results = b.add_op(a^)
    return results[0].copy()


def conv_transpose[B: GraphBackend](
    mut b: B,
    input: Value,
    filter: Value,
    strides: List[Dim],
    dilations: List[Dim],
    paddings: List[Dim],
    output_paddings: List[Dim],
    input_layout: Optional[String] = None,
) raises -> Value:
    """This op effectively computes the gradient of a convolution with respect
    to its input (as if the original convolution operation had the same
    filter and hyperparameters as this op). A visualization of the
    computation can be found in https://d2l.ai/chapter_computer-
    vision/transposed-conv.html.

    `rmo.conv_transpose` (`ConvTransposeOp`); result types inferred."""
    var a = OpArgs("ConvTransposeOp", "rmo.conv_transpose")
    a.operand("input", input)
    a.operand("filter", filter)
    a.attr_shape("strides", strides)
    a.attr_shape("dilations", dilations)
    a.attr_shape("paddings", paddings)
    a.attr_shape("output_paddings", output_paddings)
    if input_layout:
        a.attr_string("input_layout", input_layout.value())
    var results = b.add_op(a^)
    return results[0].copy()


def div[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise div operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.div` (`DivOp`); result types inferred."""
    var a = OpArgs("DivOp", "rmo.div")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def equal[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise equality comparison operation with
    implicit broadcasting and implicit dtype promotion.

    `rmo.equal` (`EqualOp`); result types inferred."""
    var a = OpArgs("EqualOp", "rmo.equal")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def greater_equal[B: GraphBackend](
    mut b: B,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """A flexible binary elementwise greater than or equal to comparison
    operation with implicit broadcasting and implicit dtype promotion.

    `rmo.greater_equal` (`GreaterEqualOp`); result types inferred."""
    var a = OpArgs("GreaterEqualOp", "rmo.greater_equal")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def greater[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise greater than comparison operation with
    implicit broadcasting and implicit dtype promotion.

    `rmo.greater` (`GreaterOp`); result types inferred."""
    var a = OpArgs("GreaterOp", "rmo.greater")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def matmul[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """Performs general matrix multiplication with broadcasting.

    `rmo.matmul` (`MatmulOp`); result types inferred."""
    var a = OpArgs("MatmulOp", "rmo.matmul")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    var results = b.add_op(a^)
    return results[0].copy()


def max[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise max operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.max` (`MaxOp`); result types inferred."""
    var a = OpArgs("MaxOp", "rmo.max")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def max_pool[B: GraphBackend](
    mut b: B,
    input: Value,
    filter_shape: List[Dim],
    strides: List[Dim],
    dilations: List[Dim],
    paddings: List[Dim],
    ceil_mode: Bool,
) raises -> Value:
    """Computes max pooling with the given filter shape, strides, and
    dilations.

    `rmo.max_pool` (`MaxPoolOp`); result types inferred."""
    var a = OpArgs("MaxPoolOp", "rmo.max_pool")
    a.operand("input", input)
    a.attr_shape("filter_shape", filter_shape)
    a.attr_shape("strides", strides)
    a.attr_shape("dilations", dilations)
    a.attr_shape("paddings", paddings)
    a.attr_bool("ceil_mode", ceil_mode)
    var results = b.add_op(a^)
    return results[0].copy()


def min[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise min operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.min` (`MinOp`); result types inferred."""
    var a = OpArgs("MinOp", "rmo.min")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mod[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise mod operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.mo.d` (`ModOp`); result types inferred."""
    var a = OpArgs("ModOp", "rmo.mo.d")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def mul[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise mul operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.mul` (`MulOp`); result types inferred."""
    var a = OpArgs("MulOp", "rmo.mul")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def not_equal[B: GraphBackend](
    mut b: B,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """A flexible binary elementwise not equal comparison operation with
    implicit broadcasting and implicit dtype promotion.

    `rmo.not_equal` (`NotEqualOp`); result types inferred."""
    var a = OpArgs("NotEqualOp", "rmo.not_equal")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def or_[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise or comparison operation with implicit
    broadcasting.

    `rmo.or` (`OrOp`); result types inferred."""
    var a = OpArgs("OrOp", "rmo.or")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def pow[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise pow operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.pow` (`PowOp`); result types inferred."""
    var a = OpArgs("PowOp", "rmo.pow")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def rebind_tensor_shape[B: GraphBackend](
    mut b: B,
    input: Value,
    new_shape: List[Dim],
) raises -> Value:
    """Unlike `mo.rebind` this also has the semantics of doing a runtime check
    that the given shapes are compatible.

    `rmo.rebind_tensor_shape` (`RebindTensorShapeOp`); result types
    inferred."""
    var a = OpArgs("RebindTensorShapeOp", "rmo.rebind_tensor_shape")
    a.operand("input", input)
    a.attr_shape("new_shape", new_shape)
    var results = b.add_op(a^)
    return results[0].copy()


def reshape[B: GraphBackend](
    mut b: B,
    input: Value,
    new_shape: List[Dim],
) raises -> Value:
    """Returns a tensor with the same underlying data as `input`, but the shape
    of `newShape`.

    `rmo.reshape` (`ReshapeOp`); result types inferred."""
    var a = OpArgs("ReshapeOp", "rmo.reshape")
    a.operand("input", input)
    a.attr_shape("new_shape", new_shape)
    var results = b.add_op(a^)
    return results[0].copy()


def select[B: GraphBackend](
    mut b: B,
    cond: Value,
    input_x: Value,
    input_y: Value,
) raises -> Value:
    """Returns `cond ? x : y` (element-wise), where `cond`, `x` and `y` are
    input tensors.

    `rmo.select` (`SelectOp`); result types inferred."""
    var a = OpArgs("SelectOp", "rmo.select")
    a.operand("cond", cond)
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    var results = b.add_op(a^)
    return results[0].copy()


def shape_to_tensor[B: GraphBackend](
    mut b: B,
    result: TensorType,
    shape: List[Dim],
) raises -> Value:
    """Converts a statically known shape attr into a 1d tensor of the shape.

    `rmo.shape_to_tensor` (`ShapeToTensorOp`); the caller supplies the
    result type."""
    var a = OpArgs("ShapeToTensorOp", "rmo.shape_to_tensor")
    a.result("result", result)
    a.attr_shape("shape", shape)
    var results = b.add_op(a^)
    return results[0].copy()


def slice[B: GraphBackend](
    mut b: B,
    input: Value,
    starts: List[Dim],
    stops: List[Dim],
    steps: List[Dim],
) raises -> Value:
    """Returns a new tensor with a subset of the elements from an N-dimensional
    `input` tensor. The subset is chosen using the `starts`, `stops`, and
    `steps` shape attributes. Each shape attributes has N elements, one for
    each dimension of the `input` tensor.

    `rmo.slice` (`SliceOp`); result types inferred."""
    var a = OpArgs("SliceOp", "rmo.slice")
    a.operand("input", input)
    a.attr_shape("starts", starts)
    a.attr_shape("stops", stops)
    a.attr_shape("steps", steps)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def sub[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise sub operation with implicit broadcasting
    and implicit dtype promotion.

    `rmo.sub` (`SubOp`); result types inferred."""
    var a = OpArgs("SubOp", "rmo.sub")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()


def top_k[B: GraphBackend](
    mut b: B,
    input: Value,
    k: Int,
    axis: Int,
) raises -> List[Value]:
    """Computes the largest values and their corresponding indices in a tensor
    along a specified axis. Returns values sorted along the axis.

    `rmo.top_k` (`TopKOp`); result types inferred."""
    var a = OpArgs("TopKOp", "rmo.top_k")
    a.operand("input", input)
    a.attr_int("k", k)
    a.attr_int("axis", axis)
    var results = b.add_op(a^)
    return results^


def xor[B: GraphBackend](mut b: B, input_x: Value, input_y: Value) raises -> Value:
    """A flexible binary elementwise xor comparison operation with implicit
    broadcasting.

    `rmo.xor` (`XorOp`); result types inferred."""
    var a = OpArgs("XorOp", "rmo.xor")
    a.operand("input_x", input_x)
    a.operand("input_y", input_y)
    a.param_decls("output_param_decls")
    var results = b.add_op(a^)
    return results[0].copy()
